### PR TITLE
Fix issue with PGSQL migration

### PR DESCRIPTION
**Pull request by Pikkupomo**
In some cases core migration 0005 caused old problem (with pgsql)
to arise where multiple changes in model are being done in same transaction.

No ref

### CODE REVIEW

**Comment by Pikkupomo** [comment]
retest this please

**Comment by tulimaki** [comment]
Missing changelog also could this PR also introduce Travis tests with postgresql?

**Comment by Pikkupomo** [comment]
I added the changelog, but we can make the postgresql later. I created an issue for that task: https://shuupteam.atlassian.net/browse/SH-233

**Comment by tulimaki** [comment]
Cancel this for now. There have been new migrations etch. @Pikkupomo reopen when you think this is mergeable.

**Pull request closed without merging**
