### PR TITLE
Add create shipment view succeeded signal and event

### PR DESCRIPTION
**Pull request by finmaster19**
Create a new signal which is dispatched after the shipment_created
has dispatched. Connect notify script to this event so you can be sure
that every function connected to shipment_created signal has already
processed and so the shipment contains all information including data
fetched from 3rd party apis for example.

### CODE REVIEW

**Comment by finmaster19** [comment]
Here is one implementation which could fix the following problem. `ShipmentCreated` event is also connected to a `shipment_created` signal as some other functions could be, if you create a notify script, for example send email, sometimes notify script is executed before other functions connected to `shipment_created` signal are run. This causes problems with email action for example. Email is sent before other receiver functions are called and so some data could be missing from the email. Using another signal and event which are dispatched after the `shipment_created` signal should fix the problem because then we can be sure that the functions connected to `shipment_created` signal has been called and processed.

**Comment by tulimaki** [comment]
Can we move the current `shipment_created` signal? Based on the comments above it seems to be pretty useless.

**Comment by suutari-ai** [comment]
* A new signal is a good idea, but it should be fired from the same place as the shipment_created signal.
* There is no need for the new event, just connect the existing event to the new signal.
* Then this is clearly a fix and should go to 1.2 branch.

**Comment by suutari-ai** [comment]
Thanks Aleksi!

**Pull request merged**
