### PR TITLE
WIP: Django: upgrade Django version

### PR DESCRIPTION
**Pull request by jovan-shuup**
Upgrade version to ~2.2~ 2.1.8

- [x] make `python -m shuup_workbench shell` work
- [x] make `python -m shuup_workbench runserver` work
- [x] make `python -m shuup_workbench migrate` work (on clean db)
- [x] make `python -m shuup_workbench shuup_init` work
- [x] make `python -m shuup_workbench createsuperuser` work
- [x] make `/sa/login` work
- [x] Complete wizard in admin with mock data
- [x] Publish store
- [x] Register new customer
- [ ] Fix logout from /sa/ (logout as admin) `NoReverseMatch at /sa/logout/ 'admin' is not a registered namespace`(logout from front works)
- [ ] create order as a customer
- [ ]  Login again with admin and process the order at admin panel
- [ ] Fix Travis
- [ ] Check few FIXME and HACK staff related to Shuup custom code
- [ ] make unit tests work

### CODE REVIEW

**Comment by jovan-shuup** [comment]
Basic staff: https://nezhar.com/blog/upgrade-a-django-based-application-from-1-11-to-2-0/

**Comment by jovan-shuup** [comment]
Shuup has custom staff for urls so nneded to fix this

```

class AdminRegexURLPattern(URLPattern):
    def __init__(self, regex, callback, default_args=None, name=None, require_authentication=True, permissions=()):
        self.permissions = tuple(permissions)
        self.require_authentication = require_authentication
        if callable(callback):
            callback = self.wrap_with_permissions(callback)
        repath = re_path(regex, callback)
        pattern = repath.pattern
        super(AdminRegexURLPattern, self).__init__(pattern, callback, default_args, name)
```

This must be revisited

**Comment by jovan-shuup** [comment]
Also tweaked the login, but that needs to be revisited 

shuup/admin/urls.py
````
def login(request, **kwargs):
    if not request.user.is_anonymous and request.method == "POST":  # We're logging in, so log out first
        do_logout(request)
    kwargs.setdefault("extra_context", {})["error"] = request.GET.get("error")
    return LoginView.as_view()(request, **kwargs)
```

**Comment by jovan-shuup** [comment]
Blocker for wizard: FE not loaded properly due to `gettext` missing;
Probably due to some changes with JS catalog
-- investigating

**Comment by jovan-shuup** [comment]
Fix for problem with `gettext`:
```
diff --git a/shuup/utils/i18n.py b/shuup/utils/i18n.py
index 364b6f5b7..59e67c288 100644
--- a/shuup/utils/i18n.py
+++ b/shuup/utils/i18n.py
@@ -150,7 +150,8 @@ def javascript_catalog_all(request, domain='djangojs'):
     Get JavaScript message catalog for all apps in INSTALLED_APPS.
     """
     all_apps = [x.name for x in apps.get_app_configs()]
-    return JavaScriptCatalog(request, domain, all_apps)
+    js_catalog = JavaScriptCatalog(packages=all_apps, domain=domain)
+    return js_catalog.get(request)
 ```

**Comment by jovan-shuup** [comment]
Blocker for generating default staff during wizard: Direct assignment to the forward side of a many-to-many set is prohibited. For example: `carousel.shops = [shop]` should be replaced by `carousel.shops.set([shop])`

-- Now can complete the wizard

**Comment by jovan-shuup** [comment]
Note regarding dependencies: 
- upgraded only Django and DRF in the `setup.py` so far; DRF to the latest and Django to the 2.1.8 due to fact that `django-filer` doesn't support it yet. But once it does the upgrade to Django 2.2 should work out of the box

**Comment by jovan-shuup** [comment]
Next thing - Blocker for add logo and publish store: https://github.com/modlinltd/django-advanced-filters/issues/86

Hacked in: `shuup/utils/form_group.py#instantiate_forms`
by adding `use_required_attribute=False,``

```
            self._forms[name] = form_def.instantiate(
                prefix=prefix,
                data=self.data,
                files=self.files,
                group_initial=self.initial,
                use_required_attribute=False,
            )
```

**Comment by jovan-shuup** [comment]
Travis: 
```Collecting Django==2.1.8 (from shuup==1.9.3b4.post0.dev9+g118db69)

  Could not find a version that satisfies the requirement Django==2.1.8 (from shuup==1.9.3b4.post0.dev9+g118db69) ```

**Comment by jovan-shuup** [comment]
Fixed registration
- setup.py:  ’django-registration-redux==2.6',  # updated to latest for Django 2.1

Fixed products overview
- https://github.com/oscarmlage/django-cruds-adminlte/issues/48

Renamed FK.to and FK.rel to `target_field` and `remote_field`

**Comment by tulimaki** [comment]
Replaced by https://github.com/shuup/shuup/pull/1984

**Pull request closed without merging**
