### PR TITLE
Fix issue with picotable column values

### PR DESCRIPTION
**Pull request by volodymyr-code**
https://github.com/shuup/shuup/issues/1841
in check_different_types func - Manager returns '' value
which we can display to the user

### CODE REVIEW

**Comment by chessbr** [comment]
It might be wise to add a unit test to prove the bug doesn't happen anymore

**Comment by volodymyr-code** [comment]
I can add unit test at this weekends

**Comment by volodymyr-code** [comment]
> I can add unit test at this weekends

done

**Comment by chessbr** [comment]
Thank you @volodymyr-code

**Pull request merged**
