### PR TITLE
Add longitude and latitude to Address models

### PR DESCRIPTION
**Pull request by strycore**

### CODE REVIEW

**Comment by chessbr** [comment]
I think we should have just one migration file and put that `blank=True`. Please squash them.

**Comment by chessbr** [comment]
I think we should have just one migration file and put that `blank=True`. Please squash them.

**Comment by tulimaki** [comment]
And while at it squash the commits too. After the change I think this is good to go.

**Comment by strycore** [comment]
Merged and squashed everything!

**Pull request merged**
