### PR TITLE
General: add model url resolver as a setting for Front and Admin

### PR DESCRIPTION
**Pull request by chessbr**
Now it is possible to customize the way model URLs are resolved.

Replaces https://github.com/shuup/shuup/pull/1336

### CODE REVIEW

**Comment by chessbr** [comment]
Thanks @soulilya for the contribution.

**Comment by chessbr** [comment]
LGTM. What do you think @tulimaki ?

**Comment by tulimaki** [comment]
I guess this is ok. Would be even better if this was done with providers. So basically I would be able to provide model url resolver from my app. And then we loop all provided resolves until the url is resolved for the model.

But like said I think this is still better than the old one. @chessbr

**Comment by chessbr** [comment]
Yeah, that would be really better. @tulimaki I will change this soon then.

**Pull request merged**
