### PR TITLE
Travis: Make test runs faster (SHUUP-2846)

### PR DESCRIPTION
**Pull request by suutari-ai**
* Use tox for testing
* Rewrite tox.ini with additional environments and some other improvements.
* Disable migrations while testing

### CODE REVIEW

**Comment by suutari-ai** [comment]
This needed some changes for the Jenkins configuration too. Let's try again...

**Comment by suutari-ai** [comment]
retest this please

**Comment by suutari-ai** [comment]
Jenkins is still configured to run the tests with migrations enabled so it will take long. I didn't want to disable migrations there, since it's better to have at least one test runner that checks the migrations too.

**Comment by Pikkupomo** [comment]
ok, lets try this then!

**Pull request merged**
