### PR TITLE
Dashboard chart fix (SH-524)

### PR DESCRIPTION
**Pull request by strycore**

### CODE REVIEW

**Comment by chessbr** [comment]
If I am not wrong, the initial requirement for this chart was to show data only for the current year.

**Comment by strycore** [comment]
Yes, that's how it was initially coded, after discussing this with @tulimaki we figured it made more sense to display the past 12 months instead future months if 12 months were to be shown at all time.

**Comment by chessbr** [comment]
Could not figure out why this fixes this: https://github.com/shuup/shuup/issues/986
It's because of a missing semicolon?

**Comment by strycore** [comment]
No, the semicolon and formatting stuff was only to get rid of warnings displayed by my editor, the actual fix is to display 12 months of data consistently.

**Comment by chessbr** [comment]
Need to fix errors so we can merge this.

**Comment by chessbr** [comment]
You can also squash commits since it is a single and simply functionality.

**Pull request merged**
