### PR TITLE
Fix wrong ISO-4217 validation

### PR DESCRIPTION
**Pull request by l0rn**
should solve #974 , though i don't know possible implications

### CODE REVIEW

**Comment by chessbr** [comment]
You're right! Looks good, thanks!

**Comment by chessbr** [comment]
Before merging this, I would ask you to amend the commit message to follow our standard. Something like:
```
Fix wrong ISO-4217 validation

Currencies should be checked against currencies map instead currencies symbols map.
```

**Comment by l0rn** [comment]
Gonna do that.... Still i'm not sure if some functionality relies on the currency symbols. If so that of course will remain a problem if you try to use CHF for which babel won't provide symbols

**Comment by chessbr** [comment]
I tested it here:
```
>>> from shuup.utils.money import Money
>>> from shuup.utils.i18n import format_money
>>> money = Money(23.32, 'CHF')
>>> print(format_money(money))
CHF 23.32
>>> money = Money(23.32, 'USD')
>>> print(format_money(money))
$ 23.32
>>> money = Money(23.32, 'DOESNTEXIST')
>>> print(format_money(money))
DOESNTEXIST 23.32
```
Babel will use the currency code to format the amount. So it should not be a problem when the currency symbol does not exist. :)

**Pull request merged**
