### PR TITLE
Core: enable ForeignKey constraint for SQLite database backends

### PR DESCRIPTION
**Pull request by chessbr**
This prevents bugs when developing and prevents errors when in production

### CODE REVIEW

**Comment by Pikkupomo** [comment]
Can you rebase this

**Comment by tulimaki** [comment]
Not sure. Is the core ready really right spot for this? Should this be behind debug mode or something? Sounds like a dev thing that is now checked and added too every time app is loaded no matter what.

Or maybe add this for tests only and then rest should be devs responsibility to add if he believes he needs it.

**Comment by chessbr** [comment]
Right @tulimaki I moved that to tests only. I put it on core because of these points:

* It checks whether it is SQLite, so if it is sqlite, you are probably running in dev mode. And even if you are running in a bizarre sqlite production, you want this foreign key constraint to be enabled to prevent objects with wrong values
* It will be enabled for all Shuup apps and for any custom app, by default, the same way other database backends does (like mysql)

**Comment by tulimaki** [comment]
Travis in bad mood. Should be fine.

**Pull request merged**
