### PR TITLE
Add Django 1.8 support back

### PR DESCRIPTION
**Pull request by suutari-ai**
Mark Django 1.8 as supported in setup.py and add test matrix for testing
Shuup with Django 1.8 and 1.9 by Tox and Travis.

### CODE REVIEW

**Comment by JoaRiski** [comment]
Some tests likely will need fixing, but 👍 for the initiative

**Comment by suutari-ai** [comment]
@JoaRiski: I got the idea that you're about to fix the tests for this... Did you fix them already to some branch? If you have the fixes already, maybe you could create another PR with the fixes and cherry-pick this commit on top of it. (This should be closed then, of course.)

If you don't have the fixes already, I may also implement them when the time permits...

**Comment by tulimaki** [comment]
@suutari-ai @JoaRiski  Let me know how limited your time is. I think this should be included on next release and if you are not going to fix this soon then maybe me, @Pikkupomo or @gurch101 should fix the tests.

**Comment by JoaRiski** [comment]
@tulimaki I'm currently working mainly on this, unless I get some high priority issues assigned to me that I must solve first.

Feel free to contribute if you feel the progress is too slow of course, I'll be committing my changes whenever I do make them.

**Pull request closed without merging**
