### PR TITLE
Admin: carousel improvements

### PR DESCRIPTION
**Pull request by chessbr**
### Admin: fix color widget
Make Bootstrap Colorpicker addon work again

### Front: fix carousel admin
- Add button to delete added slides
- Fix formset to start with index zero when adding the first slide
- Do not show delete checkbox on brand new slides

Refs ENT-2720

### CODE REVIEW

**Comment by tulimaki** [comment]
Consider just skipping the carousel admin tests for Travis in case passes nicely on locale.

**Comment by Pikkupomo** [comment]
The dot seems a bit off:
image

when using settings like this for slide:
image

**Comment by Pikkupomo** [comment]
Not an issue of this PR per se, but when clicking the dot, the `:focus` state is a a bit ugly 
image

**Comment by Pikkupomo** [comment]
Should work now.

**Pull request merged**
